### ISSUE TITLE
Authors page meaningless loops

### ISSUE THREAD

**Issue by ysnghr** [nasibovv/pragmatechBlog#12]
>     
    real_temp2 = list()
    temp = userInfo.query.with_entities(userInfo.id).all()
    temp2 = articles.query.with_entities(articles.writer_id).all()
    blogs = articles.query.all()

    for x in range(len(temp2)):
        if blogs[x].active == True:
            real_temp2.append(blogs[x].writer_id)
    
    writer = list()
    authors = list()

    for x in range(len(real_temp2)):
        for y in range(len(temp)):
            if temp[y][0] == real_temp2[x]:
                writer.append(temp[y][0])

    writer = list(set(writer))
    post_bywriter = list()

    for x in writer:
        authors.append(userInfo.query.get(x))
    
    print(temp2)

    for y in range(len(writer)):
        count = 0
        for x in range(len(temp2)):
            if writer[y] == blogs[x].writer_id:
                if blogs[x].active == True:
                    count += 1
        
        post_bywriter.append(count)

Bu koda nə ehtiyac var?

Query eləmək əvəzinə döngü yaratmaq applicationun sürətini azaldır.

Çox gərəksiz koddur. Düzəliş olunmalıdır!

**Comment by nasibovv** [comment]
Done!
