### ISSUE TITLE
Non-activated blog page

### ISSUE THREAD

**Issue by ysnghr** [nasibovv/pragmatechBlog#14]
Aktiv olmayan bloqa request vasitəsiylə çatmaq olur hansı ki o bloq hələ admin tərəfindən təsdiq olunmayıb.

sadəcə həmin məqalənin idsini blog requestinə atmaq lazımdır.

http://127.0.0.1:5000/blog/27

Məsəlçün mənim databasimdə 27 nömrəli bloq aktiv olmayıb amma mən onu başqa hesabdan oxuya bilirəm. Hansı ki bu absurddur.

**Comment by nasibovv** [comment]
Done!
