### ISSUE TITLE
Load More

### ISSUE THREAD

**Issue by ysnghr** [nasibovv/pragmatechBlog#3]
Ən sonuncu dataları gətirdikdən sonra load more butonu itməlidir. 

Hal-hazırda ən sonuncu datalar gəldikdən sonra load more butonu gəlir. Lakin klik etdikdən sonra heç bir data gəlmir və load more butonu yoxa çıxır.

Amma əslində ən sonuncu dataları gətirdikdən sonra yoxa çıxmalıdır.

**Comment by nasibovv** [comment]
Done!
