### ISSUE TITLE
Registration page

### ISSUE THREAD

**Issue by ysnghr** [nasibovv/pragmatechBlog#7]
Frontda əvvəlcə validation olmalıdır daha sonra backendə request getməlidir.

Hər hansı bir required fielda data əlavə etmədən submit etdiyim zaman əvvəl girdiyim bütün datalar silinir. Bunu düzəltmək lazımdır ki hansını yanlış girmişəmsə o barədə error görsənsin və sadəcə ona düzəliş edib yenidən submit edə bilim.

Mobile phone olan fieldda hərflər girə bilirəm. Halbuki girməyim mümkün olmamalıdır. Buraya regex yazılmalıdır.

Eyni adlı user qeydiyyatı zaman məni login səhifəsinə göndərir halbuki bu yanlışdır. Mən yeni user olaraq həmin adın olub olmadığından xəbərim olmadığı təqdirdə yeni hesab açıramsa mənasız yerə loginə göndərilməyim yanlışdır. Burada əslində əgər eyni adlı user varsa registration page qayıtmalı və həmin fieldın altında bu ad var başqa ad seçin yazılmalıdır. Amma eyni şəkildə digər inputlardakı datalar qalmalıdır. Təmizlənməli deyil.

**Comment by nasibovv** [comment]
Phone Validation Done!
